"""empty message

Revision ID: 946a35e29054
Revises: 
Create Date: 2017-08-16 09:56:29.706566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '946a35e29054'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('current_post_id', sa.Integer(), nullable=True),
    sa.Column('next_post_id', sa.Integer(), nullable=True),
    sa.Column('pre_post_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('profile', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'profile')
    op.drop_table('series')
    # ### end Alembic commands ###
